### ISSUE TITLE
rsct

### ISSUE THREAD

**Issue by kitty-catt** [ocp-power-automation/ocp4-upi-powervs#411]
# on the bastion:
yum install http://public.dhe.ibm.com/software/server/POWER/Linux/yum/download/ibm-power-repo-latest.noarch.rpm
yum install -y rsct.basic rsct.core rsct.core.utils rsct.opt.storagerm usrsctp

# on the ocp nodes, it seems to me that this would go via machineconfig one day. 

Currently only usbguard is available according to the docs.

In pseudo code ():

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 80-worker-extensions
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
    - rsct.basic 
    - rsct.core 
    - rsct.core.utils
    - rsct.opt.storagerm
    - usrsctp
```
